development:
  # Trust in Lacuna Test PKI (for development purposes only!)
  trust_lacuna_test_root: true
  # THIS SHOULD NEVER BE USED ON A PRODUCTION ENVIRONMENT!

  # REST PKI parameters
  # -------------------
  rest_pki:
    # ======================================================
    #       >>>> PASTE YOUR REST PKI ACCESS TOKEN BELOW <<<<
    # ======================================================
    access_token: '1xH6I6YpLDvkmeVyxxYsMYyfJ1GW1fRVJtAKHVhLwM1ePfmhKqeBPBaouEQ6PADURuYG5UDkoNchSw2D6vziKp9FdYJxfm_LmNQ4OJFIUOxqq2iRBIkm2aHhMHRGzoDxVRYSwLuXeJ0mcxLYy5XRFiw8mYBdiSnr47RSz9aWTq5QZQ3tykWooywUlW-TW18m7GokZO8Rgl4JYFsyLwiuwBNjqmbRf2X8fA6P26ydLSaI5kCFOi-MksPmMtySbineMdq85rObC2hOcQZnTR-DCfcteTr7cd4rqxA0hqIKKl__XGFo52ebgc6etO97zyak2NN-hlitZwAa_IymsqBjuRraBSbAwOc63tIVx9sZL1vXKZ1RlVxBMNLDpyEjIFOu60uOk0yq5oECK0cNlFlcLt288eGTyMQFOAkMoH347IHuLSgPvem4BoLxSdL-l8W03UYICenJ5pB5t6IbYSJeNMhaU5Fda90PjoYOo6YzY9ORHqLLaw1Ulx3Lcbto23l4DQ9-3g'
    # This is a TRIAL token. It will expire at 01/06/2026. If the REST PKI
    # sample doesn't work, please contact our support by email:
    # suporte@lacunasoftware.com

    # In order to use this sample on a "on premises" installation of
    # REST PKI, fill the field below with the URL address of your REST PKI
    # installation (with the trailing '/' character).
    endpoint:

  # PKI Express parameters
  # ----------------------

  pki_express:
    # List of custom trusted roots. In this sample, we will get the certificate
    # files from private/ folder.
    trusted_roots: []

    # Offline mode. Set this, if you want that PKI Express to run on offline
    # mode. This mode is useful when there is no network available.
    offline: false

  # Web PKI parameters
  # ------------------

  web_pki:
    # Base64-encoded binary license for the Web PKI. This value is passed to
    # Web PKI component's constructor on JavaScript.
    license:

test:
  trust_lacuna_test_root: true

production:
  trust_lacuna_test_root: false
