development:
  # Trust in Lacuna Test PKI (for development purposes only!)
  trust_lacuna_test_root: true
  # THIS SHOULD NEVER BE USED ON A PRODUCTION ENVIRONMENT!

  # REST PKI parameters
  # -------------------
  rest_pki:
    # ======================================================
    #       >>>> PASTE YOUR REST PKI ACCESS TOKEN BELOW <<<<
    # ======================================================
    access_token: 's_r-p0jjF0zdMxr7K5c4_IRgkgYb02JfZgxTEvuR0oubEtfhwf5Yza-R0vUgBGdaItwylFUx5BKAc5j_9SSzYkDrNAS1a-uOOdl-oPzEu7NDcAm1gcpKgw910rNl0I3GPPcXvoBF0z_fN_M70ZU5_2m9W_nZUc-SSN0z_HMhuzBr2NiC0OWhEUlecqnbeqah6S6QD7f2Ziau_7oQSI8XamA9v3nhuI6CYoo8Yp4XC1NLxHBVdXcBeWrVob3YhKCyC1Ak3d-guHp0OE29ToiiRzUylsQeJ44hMdFll7Z0jVJvNvCQXUV7A7MQIGAmMKpkVfPfNFpSlPA0HITsL1jHdmGFgBM5B4nCC_FbT7dNOVSDsM6K8uMAkX6pVvn7tc82ALqXrG9ei5XtWSqgnannSjkTVwEaaU_ONiEwZxlcs9ufHSDLXoQxDy9xuoUaC7CMM_zUOKpy7cM7JaHW30hPOFrAHasQZVDO9ai02KRN5HEKWzOMmLh47pJz62XoKubSlHz9Cw'
    # This is a TRIAL token. It will expire at 31/05/2026. If the REST PKI
    # sample doesn't work, please contact our support by email:
    # suporte@lacunasoftware.com

    # In order to use this sample on a "on premises" installation of
    # REST PKI, fill the field below with the URL address of your REST PKI
    # installation (with the trailing '/' character).
    endpoint:

  # PKI Express parameters
  # ----------------------

  pki_express:
    # List of custom trusted roots. In this sample, we will get the certificate
    # files from private/ folder.
    trusted_roots: []

    # Offline mode. Set this, if you want that PKI Express to run on offline
    # mode. This mode is useful when there is no network available.
    offline: false

  # Web PKI parameters
  # ------------------

  web_pki:
    # Base64-encoded binary license for the Web PKI. This value is passed to
    # Web PKI component's constructor on JavaScript.
    license:

test:
  trust_lacuna_test_root: true

production:
  trust_lacuna_test_root: false
