development:
  # Trust in Lacuna Test PKI (for development purposes only!)
  trust_lacuna_test_root: true
  # THIS SHOULD NEVER BE USED ON A PRODUCTION ENVIRONMENT!

  # REST PKI parameters
  # -------------------
  rest_pki:
    # ======================================================
    #       >>>> PASTE YOUR REST PKI ACCESS TOKEN BELOW <<<<
    # ======================================================
    access_token: 'rG6c0v-b05TNE0yPA12q7ovoPQx_iiKrh7tuEdSptMQ-NnrEwNU3rI2TVh4gXJXNSRU1DIaf8mdwgHHXaeysAJO2BtbMdq_jU4SNwBIDaPB7_C1_XUFbeR900MCu-aT4DmTnLQ7feWWFAGOUAF3Uxgs3BBJ4b0OG3Y50ucODr4c3MjZJFe6G_08UzvlzqWf7eI4eHTNK7NYH0d7Z0dWaPs5XiElOgWKJdCUuJCIFpmzs43Li-jZzYJR0vCml4oZZzo8TH1zScXXEpGGxZsUKxZ8Pi8XX4jxdUlaf7Y99DcyG-SIZ1UpoE_N0P72eqf7A42SJBNabIkhB5WrzcKN5jWza1Eba67OMqRYEtqLnfHT2AznqLojKFPbn5KPgO1_r2Ecfn_fM2b_cqp2mtzEuJtIDGZ791ke7jmQHARs0K2MLV41fHmprYMMg2NahDqvQeCGbX4LKBzHqcEw640CRAa_aAsFV67fQ2fe2PAPE8G__C90cJ_j7Z4fxcRyogA2WPa1I2w'
    # This is a TRIAL token. It will expire at 30/04/2026. If the REST PKI
    # sample doesn't work, please contact our support by email:
    # suporte@lacunasoftware.com

    # In order to use this sample on a "on premises" installation of
    # REST PKI, fill the field below with the URL address of your REST PKI
    # installation (with the trailing '/' character).
    endpoint:

  # PKI Express parameters
  # ----------------------

  pki_express:
    # List of custom trusted roots. In this sample, we will get the certificate
    # files from private/ folder.
    trusted_roots: []

    # Offline mode. Set this, if you want that PKI Express to run on offline
    # mode. This mode is useful when there is no network available.
    offline: false

  # Web PKI parameters
  # ------------------

  web_pki:
    # Base64-encoded binary license for the Web PKI. This value is passed to
    # Web PKI component's constructor on JavaScript.
    license:

test:
  trust_lacuna_test_root: true

production:
  trust_lacuna_test_root: false
